### 导入包，构造数据

In [13]:
import numpy as np

a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

### 花式切片

In [10]:
a[1,2]

6

In [11]:
a[:,2]

array([3, 6])

In [12]:
a[:,::2]

array([[1, 3],
       [4, 6]])

### 拼接

In [16]:
# 列对齐，增加行数
res = np.concatenate((a,b),axis=0)
res

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
# 行对齐，增加列数
res = np.concatenate((a,b),axis=1)
res

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 维度变换

In [19]:
# 降维成一维
c = a.flatten()
c

array([1, 2, 3, 4, 5, 6])

In [21]:
#　转置
c = a.T
c

array([[1, 4],
       [2, 5],
       [3, 6]])